config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :movies do
    collection do
      get 'search'
    end
    resources :reviews, except: [:show, :index]
  end

  root "movies#index"
end

app/models/movie.rb
class Movie < ActiveRecord::Base
  searchkick
  belongs_to :user
  has_many :reviews

  validates :title, presence: true,length: { minimum: 1 }
  validates :description, presence: true,length: { minimum: 5 }
  validates :director, presence: true,length: { minimum: 3 }
  validates :movie_length, presence: true
  validates :raing, presence: true
  has_attached_file :image, styles: { medium: "400x600#"}
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :movie
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :movies
  has_many :reviews, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :find_movie, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :index]

  def search
    if params[:search].present?
      @movies=Movie.search(params[:search])
    else
      @movies=Movie.all
    end
  end

  def index
    @movies = Movie.all
  end

  def show
    @reviews=@movie.reviews.order(created_at: :desc)
    if @reviews.blank?
      @avg_reviews=0
    else
      @avg_reviews = @reviews.average(:rating).round(0)
    end
  end

  def new
    @movie =current_user.movies.build
  end

  def edit
  end

  def create
    @movie = current_user.movies.build(movie_params)
      if @movie.save
        redirect_to @movie, notice: 'Movie was successfully created.'
      else
        render 'new'
      end
  end

  def update
    if @movie.update(movie_params)
      redirect_to @movie, notice: 'Movie has been updated successfully.'
    else
      render 'edit'
    end
  end

  def destroy
    @movie.destroy
      redirect_to movies_url, notice: 'Movie was successfully destroyed.'
  end

  private
    def find_movie
      @movie = Movie.find(params[:id])
    end

    def movie_params
      params.require(:movie).permit(:title, :description, :movie_length, :director, :raing, :image)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]
  before_action :set_movie
  before_action :authenticate_user!, except: [:show]


  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.user_id = current_user.id
    @review.movie_id = @movie.id
      if @review.save
       redirect_to @movie, notice: 'Review was successfully created.'
      else
        render 'new'
        render @review.errors
      end
  end

  def update
      if @review.update(review_params)
        redirect_to @movie
      else
        render 'edit'
        render @review.errors
      end
  end

  def edit
  end

  def destroy
    @review.destroy
    redirect_to @movie, notice: 'Review was successfully destroyed.'
  end

  private
    def set_review
      @review = Review.find(params[:id])
    end

     def set_movie
      @movie = Movie.find(params[:movie_id])
    end

    def review_params
      params.require(:review).permit(:rating, :comment)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
  def correct_user?(user)
    current_user == user
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/_header.html.haml
%nav.navbar.navbar-default
  .container-fluid
    .navbar-header
      %button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      .navbar-brand= link_to "Movie Rating",root_path
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      %ul.nav.navbar-nav
      %form.navbar-form.navbar-left
        .form-group
          =form_tag search_movies_path,method: :get, class:"navbar-form navbar-right", role: "search" do
            %p
              =text_field_tag :search, params[:search],class: "form-control"
              =submit_tag "Search", name: nil, class: "btn btn-default"
      %ul.nav.navbar-nav.navbar-right
        -if !user_signed_in?
          %li= link_to "Sign In",user_session_path
          %li= link_to "Sign Up",new_user_registration_path
        -else
          %li= link_to "New Movie",new_movie_path
          %li.dropdown
            %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
              Account
              %span.caret
            %ul.dropdown-menu
              %li= link_to "Profile",edit_user_registration_path

              %li.divider{:role => "separator"}
              %li= link_to "Sign Out",destroy_user_session_path, method: :delete
    / /.navbar-collapse
  / /.container-fluid

app/views/layouts/application.html.haml
!!!5
%html
%head
  %title>Movie Review</title>
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags
%body
  =render 'layouts/header'
  .container
    -flash.each do |name, msg|
      = content_tag(:div, msg, class: "alert alert-success")
    =yield

app/views/movies/_form.html.haml
= form_for @movie, html: { multipart: true, class: 'form-horizontal' } do |f|

  -if @movie.errors.any?
    #error_explanation
      %h2= "#{pluralize(@movie.errors.count, 'error')} prohibited this movie from being saved:"
      %ul
        -@movie.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :title
    %br
    = f.text_field :title,class: "form-control"
  .field
    = f.label :description
    %br
    = f.text_area :description,class: "form-control"
  .field
    = f.label :movie_length
    %br
    = f.text_field :movie_length,class: "form-control"
  .field
    = f.label :director
    %br
    = f.text_field :director,class: "form-control"
  .field
    = f.label :rating
    %br
    = f.text_field :raing,class: "form-control"
  .field
    = f.label :image
    %br
    = f.file_field :image
  .action
    %br
    = f.submit class: "btn btn-primary"

app/views/movies/edit.html.haml
=render 'form'
=link_to "Cancel and Go Back",@movie

app/views/movies/index.html.haml
-if !user_signed_in?
  .jumbotron
    %h1 Your Favorite Movies Reviewed
    %p Latest movie reviews, Hindi film reviews, English film reviews, Bollywood film reviews, Hollywood film reviews, movie ratings at Movie Ratings
    %p=link_to "Sign Up To Write A Review",new_user_registration_path, class: "btn btn-primary btn-lg signup"
.row
  -@movies.each do |movie|
    .col-sm-6.col-md-3
      .thumbnail
        =link_to (image_tag movie.image.url(:medium)), movie, class: 'image'

app/views/movies/new.html.haml
%h1.field New Movie
= render 'form'
= link_to 'Back', movies_path

app/views/movies/show.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <div class="row">
      <div class="col-md-4">
        <%= image_tag @movie.image.url(:medium) %>
        <div class="star-rating" data-score="<%= @avg_reviews %>"></div>
        <em><%= "#{@reviews.length} reviews"%> </em>
        <div class="table-responsive">
          <table class="table">
            <tbody>
              <tr>
                <td>
                  <strong>Title:</strong>
                </td>
                <td>
                  <%= best_in_place @movie, :title %>
                </td>
              </tr>
              <tr>
                <td>
                  <strong>Description:</strong>
                </td>
                <td>
                  <%= best_in_place @movie,:description %>
                </td>
              </tr>
              <tr>
                <td>
                  <strong>Movie length:</strong>
                </td>
                <td>
                  <%= best_in_place @movie,:movie_length %>
                </td>
              </tr>
              <tr>
                <td>
                  <strong>Director:</strong>
                </td>
                <td>
                  <%= best_in_place @movie,:director %>
                </td>
              </tr>
              <tr>
                <td>
                  <strong>Rating:</strong>
                </td>
                <td>
                  <%= best_in_place @movie,:raing %>
                </td>
              </tr>
            </tbody>
          </table>
          <%= link_to "Write Review",new_movie_review_path(@movie),class: 'btn btn-xs btn-danger',remote: true,                                                    id: "new_#{@movie.id}" %>
          <%= link_to 'Edit Movie ', edit_movie_path(@movie),class: "btn btn-xs btn-success" %>
          <%= link_to 'Back', movies_path,class: "btn btn-xs btn-primary" %>
          <br/>
        </div>
      </div>
      <div class="col-md-7 col-md-offset-1">
        <div class="review_title">
          <%= @movie.title %>
        </div>
        <p>
          <%= @movie.description %>
        </p>
        <% if @reviews.blank? %>
          <h3>No reviews just yet, would you like to add the new review?</h3>
          <%= link_to "Write Review",new_movie_review_path(@movie),class: 'btn btn-danger' %>
        <% else %>
        <% end %>
        <% @reviews.each do |review| %>
          <div class="reviews">
            <div class="star-rating" data-score="<%= review.rating %>"></div>
            <p>
              <%= review.comment %>
            </p>
            <%= link_to 'Edit',  edit_movie_review_path(@movie, review),remote: true, class: "btn btn-xs btn-success", id: "edit_#{review.id}" %>
            <%= link_to 'Delete', [@movie, review] ,method: :delete, class: "btn btn-xs btn-danger" %>
          </div>
          <br/>
          <br/>
        <% end %>
      </div>
    </div>
  </div>
</div>

<script>
  $('.star-rating').raty({
  path:'/assets/',
  readOnly:true,
  score:function(){
     return $(this).attr('data-score');
  }
  });
</script>

app/views/reviews/_edit.html.haml
%h1.field Editing Review
= render 'form'

app/views/reviews/_form.html.erb
<%= form_for([@movie, @review]) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <div id="star-rating"></div>
  </div><br>
  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_area :comment,class: "form-control" %>
  </div><br>
    <div class="actions">
    <%= f.submit class: "btn btn-primary btn-xs"%>
    <%= link_to 'Cancel', @movie, class: "btn btn-xs btn-default"%>
  </div><br>

<% end %>


<script>
  $('#star-rating').raty({
    path:'/assets/',
    scoreName: 'review[rating]'
  });
</script>

app/views/reviews/_new.html.haml
%h1.field New Review
= render 'form'

app/views/reviews/edit.html.erb
<h1 class="field">Editing Review</h1>

<%= render 'form' %>

app/views/reviews/edit.js.erb
$("#edit_<%= @review.id%>").replaceWith("<%= escape_javascript(render 'edit') %>")

app/views/reviews/new.html.erb
<h1 class="field">New Review</h1>

<%= render 'form' %>

app/views/reviews/new.js.erb
$("#new_<%= @movie.id%>").replaceWith("<%= escape_javascript(render 'new') %>")